name: qyre_test_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.3
  flutter_bloc: ^8.1.1
  auto_route: ^5.0.1
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  integration_test:
    sdk: flutter
  build_runner: ^2.2.1
  auto_route_generator: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/fonts/
  fonts:
    - family: Matter
      fonts:
        - asset: assets/fonts/matter-light.woff
          weight: 300
        - asset: assets/fonts/Matter-Regular.woff
          weight: 400 
        - asset: assets/fonts/matter-medium.woff
          weight: 500
        - asset: assets/fonts/Matter-SemiBold.woff
          weight: 600
        - asset: assets/fonts/Matter-Bold.woff
          weight: 700